### ISSUE TITLE
Items not appearing correctly in milestone

### ISSUE THREAD

**Issue by Majesty07** [TheFarawayDev/Better_Recipes_x10#3]
items aren't showing correctly in milestone select tab after you click on Tier 1 then Tier 0, i switched from my main save to a new one the issue still happens, also would recommend setting the unlock wait time to at least 1minute so the game doesn't bug out.

![Screenshot 2024-10-14 151356](https://github.com/user-attachments/assets/034c9af5-a598-4e21-8853-5a2249a624f8)

**Comment by TheFarawayDev** [comment]
I will look into this and resolve it immediately likely moving the SAM items to a later tier for balancing and move tier 0 to 1 as it may be a simple bug when skipping onboarding!
