### ISSUE TITLE
Fluids like Oil, Fuel required 0 source

### ISSUE THREAD

**Issue by Xenom555** [TheFarawayDev/Better_Recipes_x10#4]
Hi, Dev

I noticed that your recipes requires 0 resources almost on all liquid recipes which seems to be bug. I think is will be fine to have some requirements for example 3 oil = 60 Plastic and 20 Residual Oil.

Thank you

**Comment by TheFarawayDev** [comment]
Well it is meant to be a 1 --> 10 ratio I plan to add a feature to adjust the value for it in a configuration! And I will look into the issue though I haven't seen this problem I will attempt to try on the main PC!

**Comment by TheFarawayDev** [comment]
**ISSUE RESOLVED**

**Comment by Xenom555** [comment]
@TheFarawayDev  Thank you. I love your recipe mod. You can make a lot alternative options. when 1 option is 4x less resources on input and vanilla on output or vanilla input but 4x all on output but fluid is tricky because you are always limited to 600m3 per min. If you dont want use another conversion mods.

**Comment by TheFarawayDev** [comment]
Hey Xenom if you wouldn't mind could you be my tester for the upcoming configuration update?

Menu Options would be:
- Normal Input -> 10x
- 10x -> Normal Output
- 1:10 Ratio
- 10:1 Ratio
- 4x -> Normal Output
- Normal Input -> 4x

**Comment by Xenom555** [comment]
Hi. Yes i can test your recipes. But i think if is possible to make config menu where user can set own multiplies on input also output side this way you solve alll issues. Every one can set your settings. Even all alternative recipes from vanilla game can be done this way.

**Comment by Xenom555** [comment]
> Hey Xenom if you wouldn't mind could you be my tester for the upcoming configuration update?
> 
> Menu Options would be:
> 
> * Normal Input -> 10x (Vanilla ++)
> * 10x -> Normal Output (Hard Mode Plus)
> * 1:10 Ratio (Default)
> * 10:1 Ratio (Are You Insane?)
> * 4x -> Normal Output (Hard Mode)
> * Normal Input -> 4x (Vanilla +)
> 
> All the (Insert Mode Name) is what it will show as the options with ofc descriptions to show what each one does.

Yes. but i think better do it that user can configure whole settings so you don't need to create 6 versions. Every one can set own settings. It is better for maintenance because you have 1 source code and this source code is only modified by user settings. So every change you need to modify only source code. If you have 6 different settings and someone will report bug you need to fix all 6 versions. I think in long run is better for you and uses to set setting on own. But i don't know if is possible. I have several mods where i can set own settings but nobody do it on recipes.

**Comment by TheFarawayDev** [comment]
@Xenom555 [Join the discord!](https://discord.gg/HqeueQg3AS)

**Comment by TheFarawayDev** [comment]
Also looky![image](https://github.com/user-attachments/assets/34ce3e35-bc05-425a-99a8-dc58da0a222a)!
