### ISSUE TITLE
alumina solution

### ISSUE THREAD

**Issue by HappyTheCow** [TheFarawayDev/Better_Recipes_x10#5]
**Describe the bug**
the aluminia solution is out putting 0.06 m3 base

**To Reproduce**
i set up a separate refinery to test with a tank to see if its just a text display issue, but its not filling the tank

**Expected behavior**
producing more than the base game recipe

**Desktop (please complete the following information):**
 - Version 1.0.0.4 build 372858
 - sml v.3.8.0+483
![image](https://github.com/user-attachments/assets/6d6b8171-00a5-4376-9c07-a69b7c424858)

**Comment by TheFarawayDev** [comment]
Will work on this immediately, thought I had resolved such issue guess I missed a spot.

**Comment by HappyTheCow** [comment]
Tyvm! now that's what i call a speedy response time dang you're fast
