### ISSUE TITLE
Thermal propulsion rockets missing?

### ISSUE THREAD

**Issue by HappyTheCow** [TheFarawayDev/Better_Recipes_x10#6]
Describe the bug
Thermal propulsion rockets missing from manufacturer menu

Desktop (please complete the following information):

    Version 1.0.0.4 build 372858
    sml v.3.8.0+483
![image](https://github.com/user-attachments/assets/983106df-fd7e-485f-ba50-0a204efcab4d)

**Comment by HappyTheCow** [comment]
just doubled checked, its missing in the rewards from the milestone for t8 recipes

**Comment by TheFarawayDev** [comment]
Update to version 1.1.9
